### ISSUE TITLE
Adding website link for the wikipedia button

### ISSUE THREAD

**Issue by ratishjain12** [Debangan202Ok/Data-Structure#11]
currently the wikipedia button is not leading to anywhere.

I want to add the wikipedia resource to it @Debangan202Ok

**Comment by Debangan202Ok** [comment]
> currently the wikipedia button is not leading to anywhere.
> 
> I want to add the wikipedia resource to it @Debangan202Ok 

@ratishjain12 thank you for pointing.
Work on it.

**Comment by Debangan202Ok** [comment]
> currently the wikipedia button is not leading to anywhere.
> 
> I want to add the wikipedia resource to it @Debangan202Ok 

Hii @ratishjain12 
I think someone is working on that issue.
You can check the who is working fot that.
Then go for it.

**Comment by Debangan202Ok** [comment]
@ratishjain12 thank you for contributing.
Don't forget to give a star to the contributed repository.
