### ISSUE TITLE
Adding an automatic scroll to top feature

### ISSUE THREAD

**Issue by DavOlufuwa** [Debangan202Ok/Data-Structure#13]
I can help fix the routing issue, so that when you navigate to a new page from the homepage, it will start from the top always.

**Comment by Debangan202Ok** [comment]
> I can help fix the routing issue, so that when you navigate to a new page from the homepage, it will start from the top always.
> 

@DavOlufuwa go fot it🚀
Don't forget to give a start to this repo.

**Comment by Debangan202Ok** [comment]
@DavOlufuwa Well done.feel free to make future contributions.
