### ISSUE TITLE
Adding the Hacktoberfest Topic.

### ISSUE THREAD

**Issue by DavOlufuwa** [Debangan202Ok/Data-Structure#25]
@Debangan202Ok I think you need to add the Hacktoberfest topic to the repo, so that PRs with the hacktoberfest tag can be counted. 
This is what I saw;
![Screen-shot-2023-10-06 095419](https://github.com/Debangan202Ok/Data-Structure/assets/87868500/994bfd24-b655-4264-9169-ba61111300ed)

**Comment by Debangan202Ok** [comment]
> @Debangan202Ok I think you need to add the Hacktoberfest topic to the repo, so that PRs with the hacktoberfest tag can be counted. 
> This is what I saw;
> ![Screen-shot-2023-10-06 095419](https://github.com/Debangan202Ok/Data-Structure/assets/87868500/994bfd24-b655-4264-9169-ba61111300ed)
> 

Sure! Will do it
