### ISSUE TITLE
Side navbar overlapping with Footer in Labs page

### ISSUE THREAD

**Issue by Miran-Firdausi** [Debangan202Ok/Data-Structure#27]
The side Navbar height needs to be reduced to prevent overlapping the footer.

**Comment by Debangan202Ok** [comment]
> The side Navbar height needs to be reduced to prevent overlapping the footer.

@Miran-Firdausi wanna fix it?

**Comment by Miran-Firdausi** [comment]
Will do. Assign me, I will do it tomorrow.
