### ISSUE TITLE
[UI Enhancement]: Fixing the labs page styling 

### ISSUE THREAD

**Issue by sohamtembhurne** [Debangan202Ok/Data-Structure#36]
The red border on the labs page seems very inconsistent with the overall UI design of the page.

<img src = "https://github.com/Debangan202Ok/Data-Structure/assets/82658685/0428cd2e-f833-452d-ba67-fd228f359515" width=700px />

Fix: Removing the red border and applying some styling on stack container and how it works such that the page seems more appealing would look way better and enhance the user experience

**Comment by sohamtembhurne** [comment]
I am a little busy for few days. You can assign this issue to anyone else in the mean time.

**Comment by Debangan202Ok** [comment]
> I am a little busy for few days. You can assign this issue to anyone else in the mean time. 

@sohamtembhurne okay.

**Comment by sohamtembhurne** [comment]
Hi @Debangan202Ok, I took a look at the labs page. I can see that there is no functionality associated with the sidebar . Is anyone working on it ?

**Comment by Debangan202Ok** [comment]
> Hi @Debangan202Ok, I took a look at the labs page. I can see that there is no functionality associated with the sidebar . Is anyone working on it ?

Hlw @sohamtembhurne , no one working on it. Currently I'm upgrading the whole project with nextjs. If you want to work on it then go ahead, i will merge it.

**Comment by sohamtembhurne** [comment]
ok sure

**Comment by sohamtembhurne** [comment]
Fixed in #44
