### ISSUE TITLE
[NAVBAR UI IMPROVMENT] : Navbar UI Improvment on desktop site

### ISSUE THREAD

**Issue by Ayusht777** [Debangan202Ok/Data-Structure#37]
I want to improve it navbar ui for desktop and if possible for mobile also

**Comment by Debangan202Ok** [comment]
Do it.

**Comment by Debangan202Ok** [comment]
> here it is the preview of the improve navbar 
> 
> https://github.com/Debangan202Ok/Data-Structure/assets/106388215/694a58e9-2276-4f6f-a2ac-14717262c134
> 
> 

Nice work @Ayusht777

**Comment by Ayusht777** [comment]
can you add labels like hackoctoberfest so i will easy from them to track
