### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by sohamtembhurne** [Debangan202Ok/Data-Structure#4]
I think I can improve the overall appeal of the website by adding some animations and UI changes to the navbar. @Debangan202Ok , assign me this task under the hacktoberfest tag

**Comment by Debangan202Ok** [comment]
> I think I can improve the overall appeal of the website by adding some animations and UI changes to the navbar. @Debangan202Ok , assign me this task under the hacktoberfest tag

Hlw @sohamtembhurne , sure i will assign you. Can you elaborate what kind of changes You will perform?

**Comment by sohamtembhurne** [comment]
I am planning to to use framer motion to add some scroll animations. For the navbar, a rounded navbar in center will look better.

**Comment by Debangan202Ok** [comment]
> I am planning to to use framer motion to add some scroll animations. For the navbar, a rounded navbar in center will look better.

@sohamtembhurne sounds good! Go for it🚀

**Comment by Debangan202Ok** [comment]
@sohamtembhurne thanks for your contribution. Don't forget give a start.
