### ISSUE TITLE
Resize the 2nd container in the `Home` page so that text is displayed properly.

### ISSUE THREAD

**Issue by Petrosdevri** [Debangan202Ok/Data-Structure#40]
I have a problem with viewing the 2nd container in the `Home` page. I am not sure if that's a general bug because the text appears properly in mobile devices but I think I got the abilities to work on this issue.

Screenshot for validation: 

![Screenshot 2023-10-23 at 15-19-06 Data Structure-Skillx](https://github.com/Debangan202Ok/Data-Structure/assets/100411628/81bbb771-3588-4dd6-abe7-829a6bb4a404)

**Comment by Debangan202Ok** [comment]
> I have a problem with viewing the 2nd container in the `Home` page. I am not sure if that's a general bug because the text appears properly in mobile devices but I think I got the abilities to work on this issue.
> 
> Screenshot for validation: 
> 
> ![Screenshot 2023-10-23 at 15-19-06 Data Structure-Skillx](https://github.com/Debangan202Ok/Data-Structure/assets/100411628/81bbb771-3588-4dd6-abe7-829a6bb4a404)
> 

@Petrosdevri thank you for pointing out this issue. I3f you wanna fix this then go ahead.
