### ISSUE TITLE
Ehance the README.md File

### ISSUE THREAD

**Issue by Debangan202Ok** [Debangan202Ok/Data-Structure#6]
Enhance the readme file add how to locally setup this repo for contribution & also explain the file structure.

**Comment by khushpreetsinghb** [comment]
I am new to open source, I want to work on this issue. Can you please assign this to me.

**Comment by khushpreetsinghb** [comment]
What I will explain about the file structure ?

**Comment by Debangan202Ok** [comment]
> What I will explain about the file structure ?

You have to explain tree like structure.
|
|-app
|
|-components/ui
|
|-etc...

**Comment by khushpreetsinghb** [comment]
Just need to show the structure or also explain some files ?

**Comment by Debangan202Ok** [comment]
@khushpreetsinghb well done.
It's look very nice and easy to read. You can make more contribution 😊. Don't forget to give a start on this repo.

**Comment by khushpreetsinghb** [comment]
Thank you
