### ISSUE TITLE
Button non responsive

### ISSUE THREAD

**Issue by Pooja-Lohar25** [Debangan202Ok/Data-Structure#9]
"Learn more from Wikipedia" button on home page is non responsive. 

![Screenshot 2023-10-04 204611](https://github.com/Debangan202Ok/Data-Structure/assets/73185303/ca153f2e-ca37-48d4-8ece-64071e8d4266)

@Debangan202Ok i would like to work on it kindly assign this to me under hacktoberfest.

**Comment by Debangan202Ok** [comment]
Hi @Pooja-Lohar25 ,
Thank you for pointing out.
Work on it.

**Comment by Pooja-Lohar25** [comment]
The button is responsive and works as expected. There might be some server issues at that time.

**Comment by Pooja-Lohar25** [comment]
closing the issue
